"""empty message

Revision ID: aaaaecb39ecf
Revises: 92a3db14632e
Create Date: 2025-07-04 03:02:50.261387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaaaecb39ecf'
down_revision: Union[str, None] = '92a3db14632e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stationary_assets', sa.Column('reg_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stationary_assets', 'reg_date')
    # ### end Alembic commands ###
